// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: configs/agent.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求体：车机发送给大模型算法端的数据
type IntentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`   // 用户输入的语音识别文本（例如：“我有点热，放首周杰伦的歌”）
	Status        *VehicleStatus         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // 当前车辆的实时状态（Agent 需要结合状态做上下文决策）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentRequest) Reset() {
	*x = IntentRequest{}
	mi := &file_configs_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentRequest) ProtoMessage() {}

func (x *IntentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_configs_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentRequest.ProtoReflect.Descriptor instead.
func (*IntentRequest) Descriptor() ([]byte, []int) {
	return file_configs_agent_proto_rawDescGZIP(), []int{0}
}

func (x *IntentRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *IntentRequest) GetStatus() *VehicleStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

// 车辆实时状态结构体
type VehicleStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AcTemperature int32                  `protobuf:"varint,1,opt,name=ac_temperature,json=acTemperature,proto3" json:"ac_temperature,omitempty"` // 当前空调温度
	IsWindowOpen  bool                   `protobuf:"varint,2,opt,name=is_window_open,json=isWindowOpen,proto3" json:"is_window_open,omitempty"`  // 车窗是否打开
	CurrentMedia  string                 `protobuf:"bytes,3,opt,name=current_media,json=currentMedia,proto3" json:"current_media,omitempty"`     // 当前正在播放的媒体/歌曲
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehicleStatus) Reset() {
	*x = VehicleStatus{}
	mi := &file_configs_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleStatus) ProtoMessage() {}

func (x *VehicleStatus) ProtoReflect() protoreflect.Message {
	mi := &file_configs_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleStatus.ProtoReflect.Descriptor instead.
func (*VehicleStatus) Descriptor() ([]byte, []int) {
	return file_configs_agent_proto_rawDescGZIP(), []int{1}
}

func (x *VehicleStatus) GetAcTemperature() int32 {
	if x != nil {
		return x.AcTemperature
	}
	return 0
}

func (x *VehicleStatus) GetIsWindowOpen() bool {
	if x != nil {
		return x.IsWindowOpen
	}
	return false
}

func (x *VehicleStatus) GetCurrentMedia() string {
	if x != nil {
		return x.CurrentMedia
	}
	return ""
}

// 响应体：算法端返回给车机的数据
type IntentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReplyText     string                 `protobuf:"bytes,1,opt,name=reply_text,json=replyText,proto3" json:"reply_text,omitempty"`             // 大模型或 RAG 生成的拟人化语音播报文本
	ControlAction string                 `protobuf:"bytes,2,opt,name=control_action,json=controlAction,proto3" json:"control_action,omitempty"` // 核心：大模型生成的结构化车控命令 (JSON 字符串，例如：{"action": "SET_AC", "value": 22})
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntentResponse) Reset() {
	*x = IntentResponse{}
	mi := &file_configs_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntentResponse) ProtoMessage() {}

func (x *IntentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configs_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntentResponse.ProtoReflect.Descriptor instead.
func (*IntentResponse) Descriptor() ([]byte, []int) {
	return file_configs_agent_proto_rawDescGZIP(), []int{2}
}

func (x *IntentResponse) GetReplyText() string {
	if x != nil {
		return x.ReplyText
	}
	return ""
}

func (x *IntentResponse) GetControlAction() string {
	if x != nil {
		return x.ControlAction
	}
	return ""
}

var File_configs_agent_proto protoreflect.FileDescriptor

const file_configs_agent_proto_rawDesc = "" +
	"\n" +
	"\x13configs/agent.proto\x12\acockpit\"U\n" +
	"\rIntentRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12.\n" +
	"\x06status\x18\x02 \x01(\v2\x16.cockpit.VehicleStatusR\x06status\"\x81\x01\n" +
	"\rVehicleStatus\x12%\n" +
	"\x0eac_temperature\x18\x01 \x01(\x05R\racTemperature\x12$\n" +
	"\x0eis_window_open\x18\x02 \x01(\bR\fisWindowOpen\x12#\n" +
	"\rcurrent_media\x18\x03 \x01(\tR\fcurrentMedia\"V\n" +
	"\x0eIntentResponse\x12\x1d\n" +
	"\n" +
	"reply_text\x18\x01 \x01(\tR\treplyText\x12%\n" +
	"\x0econtrol_action\x18\x02 \x01(\tR\rcontrolAction2R\n" +
	"\x0eCockpitService\x12@\n" +
	"\rProcessIntent\x12\x16.cockpit.IntentRequest\x1a\x17.cockpit.IntentResponseB:Z8github.com/kbzce745/DriveOS-LLM-Agent/backend-go/rpc;rpcb\x06proto3"

var (
	file_configs_agent_proto_rawDescOnce sync.Once
	file_configs_agent_proto_rawDescData []byte
)

func file_configs_agent_proto_rawDescGZIP() []byte {
	file_configs_agent_proto_rawDescOnce.Do(func() {
		file_configs_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configs_agent_proto_rawDesc), len(file_configs_agent_proto_rawDesc)))
	})
	return file_configs_agent_proto_rawDescData
}

var file_configs_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_configs_agent_proto_goTypes = []any{
	(*IntentRequest)(nil),  // 0: cockpit.IntentRequest
	(*VehicleStatus)(nil),  // 1: cockpit.VehicleStatus
	(*IntentResponse)(nil), // 2: cockpit.IntentResponse
}
var file_configs_agent_proto_depIdxs = []int32{
	1, // 0: cockpit.IntentRequest.status:type_name -> cockpit.VehicleStatus
	0, // 1: cockpit.CockpitService.ProcessIntent:input_type -> cockpit.IntentRequest
	2, // 2: cockpit.CockpitService.ProcessIntent:output_type -> cockpit.IntentResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_configs_agent_proto_init() }
func file_configs_agent_proto_init() {
	if File_configs_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configs_agent_proto_rawDesc), len(file_configs_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configs_agent_proto_goTypes,
		DependencyIndexes: file_configs_agent_proto_depIdxs,
		MessageInfos:      file_configs_agent_proto_msgTypes,
	}.Build()
	File_configs_agent_proto = out.File
	file_configs_agent_proto_goTypes = nil
	file_configs_agent_proto_depIdxs = nil
}
