// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: configs/agent.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CockpitService_ProcessIntent_FullMethodName = "/cockpit.CockpitService/ProcessIntent"
)

// CockpitServiceClient is the client API for CockpitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义车载智能座舱的核心服务
type CockpitServiceClient interface {
	// 核心接口：接收用户意图，返回控制指令与 RAG 文本
	ProcessIntent(ctx context.Context, in *IntentRequest, opts ...grpc.CallOption) (*IntentResponse, error)
}

type cockpitServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCockpitServiceClient(cc grpc.ClientConnInterface) CockpitServiceClient {
	return &cockpitServiceClient{cc}
}

func (c *cockpitServiceClient) ProcessIntent(ctx context.Context, in *IntentRequest, opts ...grpc.CallOption) (*IntentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IntentResponse)
	err := c.cc.Invoke(ctx, CockpitService_ProcessIntent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CockpitServiceServer is the server API for CockpitService service.
// All implementations must embed UnimplementedCockpitServiceServer
// for forward compatibility.
//
// 定义车载智能座舱的核心服务
type CockpitServiceServer interface {
	// 核心接口：接收用户意图，返回控制指令与 RAG 文本
	ProcessIntent(context.Context, *IntentRequest) (*IntentResponse, error)
	mustEmbedUnimplementedCockpitServiceServer()
}

// UnimplementedCockpitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCockpitServiceServer struct{}

func (UnimplementedCockpitServiceServer) ProcessIntent(context.Context, *IntentRequest) (*IntentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessIntent not implemented")
}
func (UnimplementedCockpitServiceServer) mustEmbedUnimplementedCockpitServiceServer() {}
func (UnimplementedCockpitServiceServer) testEmbeddedByValue()                        {}

// UnsafeCockpitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CockpitServiceServer will
// result in compilation errors.
type UnsafeCockpitServiceServer interface {
	mustEmbedUnimplementedCockpitServiceServer()
}

func RegisterCockpitServiceServer(s grpc.ServiceRegistrar, srv CockpitServiceServer) {
	// If the following call panics, it indicates UnimplementedCockpitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CockpitService_ServiceDesc, srv)
}

func _CockpitService_ProcessIntent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IntentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CockpitServiceServer).ProcessIntent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CockpitService_ProcessIntent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CockpitServiceServer).ProcessIntent(ctx, req.(*IntentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CockpitService_ServiceDesc is the grpc.ServiceDesc for CockpitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CockpitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cockpit.CockpitService",
	HandlerType: (*CockpitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessIntent",
			Handler:    _CockpitService_ProcessIntent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "configs/agent.proto",
}
