# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: configs/agent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'configs/agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63onfigs/agent.proto\x12\x07\x63ockpit\"F\n\rIntentRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12&\n\x06status\x18\x02 \x01(\x0b\x32\x16.cockpit.VehicleStatus\"V\n\rVehicleStatus\x12\x16\n\x0e\x61\x63_temperature\x18\x01 \x01(\x05\x12\x16\n\x0eis_window_open\x18\x02 \x01(\x08\x12\x15\n\rcurrent_media\x18\x03 \x01(\t\"<\n\x0eIntentResponse\x12\x12\n\nreply_text\x18\x01 \x01(\t\x12\x16\n\x0e\x63ontrol_action\x18\x02 \x01(\t2R\n\x0e\x43ockpitService\x12@\n\rProcessIntent\x12\x16.cockpit.IntentRequest\x1a\x17.cockpit.IntentResponseB:Z8github.com/kbzce745/DriveOS-LLM-Agent/backend-go/rpc;rpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'configs.agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/kbzce745/DriveOS-LLM-Agent/backend-go/rpc;rpc'
  _globals['_INTENTREQUEST']._serialized_start=32
  _globals['_INTENTREQUEST']._serialized_end=102
  _globals['_VEHICLESTATUS']._serialized_start=104
  _globals['_VEHICLESTATUS']._serialized_end=190
  _globals['_INTENTRESPONSE']._serialized_start=192
  _globals['_INTENTRESPONSE']._serialized_end=252
  _globals['_COCKPITSERVICE']._serialized_start=254
  _globals['_COCKPITSERVICE']._serialized_end=336
# @@protoc_insertion_point(module_scope)
