# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from configs import agent_pb2 as configs_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in configs/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CockpitServiceStub(object):
    """定义车载智能座舱的核心服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessIntent = channel.unary_unary(
                '/cockpit.CockpitService/ProcessIntent',
                request_serializer=configs_dot_agent__pb2.IntentRequest.SerializeToString,
                response_deserializer=configs_dot_agent__pb2.IntentResponse.FromString,
                _registered_method=True)


class CockpitServiceServicer(object):
    """定义车载智能座舱的核心服务
    """

    def ProcessIntent(self, request, context):
        """核心接口：接收用户意图，返回控制指令与 RAG 文本
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CockpitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessIntent,
                    request_deserializer=configs_dot_agent__pb2.IntentRequest.FromString,
                    response_serializer=configs_dot_agent__pb2.IntentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cockpit.CockpitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cockpit.CockpitService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CockpitService(object):
    """定义车载智能座舱的核心服务
    """

    @staticmethod
    def ProcessIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cockpit.CockpitService/ProcessIntent',
            configs_dot_agent__pb2.IntentRequest.SerializeToString,
            configs_dot_agent__pb2.IntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
